name: Node CI
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1

            - name: Create env file
                run: |
                touch .env.production.local
                echo VITE_CLOUDBASE_ENV=${{ secrets.CLOUDBASE_ENV }} >> .env.production.local
                echo VITE_CLOUDBASE_REGION=${{ secrets.CLOUDBASE_REGION }} >> .env.production.local

            - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: |
                npm install
                npm run build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: dist # The folder the action should deploy.
